spring:
  application:
    name: inventory-concurrency
  datasource:
    url: jdbc:postgresql://localhost:5432/inventory_concurrency
    username: inventory
    password: inventory
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: inventory-concurrency
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.casebook.inventoryconcurrency.stock.application

server:
  port: 8080

app:
  kafka:
    topics:
      stock-reserved: inventory-concurrency.stock-reserved
